name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Cordova
      run: |
        npm install -g cordova@12
    
    - name: Create Cordova project
      run: |
        cordova create kulguru-app com.kulguru.tracker Kulguru
        cd kulguru-app
        cp ../index.html www/
        cp ../config.xml .
        cordova platform add android
    
    - name: Build APK
      run: |
        cd kulguru-app
        cordova build android --release -- --packageType=apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kulguru-app
        path: kulguru-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Kulguru v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: kulguru-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: kulguru-v1.0.${{ github.run_number }}.apk
        asset_content_type: application/vnd.android.package-archive
